title: Karthik Mahesh's experiments
author: Karthik Mahesh
email: karthikm2297@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my homepage. You can find some of my work and my CV here
  
# social links
github_username:  karthikm2297

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-slate
